name: flutter_translate_gen
description: Statically-typed localization keys generator for flutter_translate.
version: 1.2.4
author: Florin Bratan <florin@leadcode.dev>
homepage: https://leadcode.dev
repository: https://github.com/bratan/flutter_translate_gen

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_casing: ^1.0.1
  dart_utils: ^1.0.2
  source_gen: ^1.0.0
  build: ^2.0.0
  code_builder: '>=3.2.0 <4.0.0'
  analyzer: ^1.4.0
  glob: ^2.0.1
  # TODO point to 1.0.2 as soon as it is merged
  flutter_translate_annotations:
    git: https://github.com/avbk/flutter_translate_annotations


dev_dependencies:
  build_runner: ^1.12.2
  lint: ^1.5.3
  test: ^1.16.8
